name: Lint
on:
 push:
   branches:
     - main
 pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          fetch-depth: 0
      - name: Run Lint checks
        run: |
          ./earthly.sh +lint
