name: Test
on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ci-test-${{ github.head_ref || github.ref }}-${{ github.repository }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      matrix:
        bundles:
          - calico
          - cert-manager
          - kubevirt
          - longhorn
          - metallb
          - multus
          - nginx
          - kairos
          - kyverno
          - system-upgrade-controller
          - argocd
          - "LocalAI"
          - flux
          - coco
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: docker-practice/actions-setup-docker@master
      - run: ./earthly.sh --ci --push +test --BUNDLE=${{ matrix.bundles }}
